language: php
php:
    - '8.0'

before_script:
    - composer install

script:
    - composer validate --strict
    - vendor/bin/phpunit --coverage-text
    - vendor/bin/phpcs src/ tests/

cache:
  directories:
    - $HOME/.composer/cache
